[build]
  command = "npm install expo-server && npx expo export -p web"
  functions = "netlify/functions"
  publish = "dist/client"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 404

[functions]
  included_files = ["dist/server/**/*"]
